name: av-swarmui-new

services:
  swarmui:
    image: av-swarmui
    user: 1000:1000
    cap_drop:
      - ALL
    build:
      context: ../
      args:
        UID: 1000
      #dockerfile: launchtools/StandardDockerfile.docker
      dockerfile: launchtools/OpenDockerfile.docker
    container_name: swarmui
    # uncomment `network_mode: host` if you want to access other services on the host network (eg a separated comfy instance)
    # network_mode: host
    volumes:
      - ../:/SwarmUI/
      - ./av-comfyui-extra-requirements.txt:/AV-EXTRA/av-comfyui-extra-requirements.txt
      - /mnt/AVHOM/AI/SwarmUI_New/DockerData/AVSwarmUI/:/AV-DATA/

      - /mnt/AVHOM/AI/SwarmUI_New/DockerData/AVSwarmUI/Models/:/SwarmUI/Models/
      - /mnt/AVHOM/AI/SwarmUI_New/DockerData/AVSwarmUI/swarmdata/:/SwarmUI/Data/
      - /mnt/AVHOM/AI/SwarmUI_New/DockerData/AVSwarmUI/swarmbackend/:/SwarmUI/dlbackend/
      - /mnt/AVHOM/AI/SwarmUI_New/DockerData/AVSwarmUI/swarmdlnodes/:/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes/
      - /mnt/AVHOM/AI/SwarmUI_New/DockerData/AVSwarmUI/Output/:/SwarmUI/Output/
      - /mnt/AVHOM/AI/SwarmUI_New/DockerData/AVSwarmUI/BuiltinExtensions/CustomWorkflows/:/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/CustomWorkflows/
      # - ./src/BuiltinExtensions/ComfyUIBackend/CustomWorkflows:/SwarmUI/src/BuiltinExtensions/ComfyUIBackend/CustomWorkflows
    ports:
      - "7801:7801"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # change the count to the number of GPUs you want to use.
              count: 1
              capabilities: [gpu]
# volumes:
#   swarmdata:
#     name: swarmdata
#   swarmbackend:
#     name: swarmbackend
#   swarmdlnodes:
#     name: swarmdlnodes
